### ISSUE TITLE
Uso do useOrderForm

### ISSUE THREAD

**Issue by williamcms** [gustavokei/vtex-react-checkout#1]
Olá!

Perdão se essa pergunta pode parecer trivial, mas comecei a aprender pouco mais de 2 meses durante uma migração da plataforma para IO e estou com algumas dúvidas.

- Não estou conseguindo usar o [useOrderForm.jsx](https://github.com/gustavokei/vtex-react-checkout/commit/8d1b7c8ade1c31d2545d32aad7b8643361da58b2#diff-1a67bbadb80973af3da1bbb6cfb284d85a72385eaa0ae69f6dd1cb44ea6be0bf)
- Nem mesmo importar **vtex.order-manager/OrderForm** para usar.
- Após colocar essas alterações para o LIVE/PRODUÇÃO, devo desinstalar o app oficial da vtex? Pois no meu workspace tem duas entradas que acabam compartilhando as mesmas configurações e se alterando entre si. Se puder me auxiliar nisso.

**Comment by gustavokei** [comment]
Olá @williamcms, tudo bom? Primeiramente peço desculpas pela demora para responder esta issue.
Analisei seu problema e percebi que realmente o hook [useOrderForm.jsx](https://github.com/gustavokei/vtex-react-checkout/commit/8d1b7c8ade1c31d2545d32aad7b8643361da58b2#diff-1a67bbadb80973af3da1bbb6cfb284d85a72385eaa0ae69f6dd1cb44ea6be0bf) não está funcionando corretamente.

Isto acontece porque não temos um arquivo de declaração `useOrderForm.d.ts` para o `useOrderForm.jsx`.
Implementei uma [solução paliativa no `tsconfig.json`](https://github.com/gustavokei/vtex-react-checkout/commit/7cd8d563d653fec847fa593bb9e864ad64313671).

Você pode usar o hook conforme este exemplo no [ExampleContent.tsx](https://github.com/gustavokei/vtex-react-checkout/blob/main/src/scripts/components/ExampleComponent/ExampleContent.tsx):

```js
import React, { useState, useEffect } from "react";
import { useExample } from "./context/ExampleContext";
import useOrderForm from "../../../utils/useOrderForm.jsx"; // importando o hook aqui

import { Navigation, Pagination, Scrollbar, A11y } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

const ExampleComponent = () => {
  const { exampleValue } = useExample();
  const [number, setNumber] = useState(0);

  const { orderForm } = useOrderForm();

  // console.log() toda vez que este useEffect for ativado
  // quando a página carregar e quando, por exemplo, um item for adicionado ao carrinho
  useEffect(() => {
    console.log("orderForm", orderForm);
  }, [orderForm]);

  useEffect(() => {
    setTimeout(() => {
      setNumber(number + 1);
    }, 1000);
  }, [number]);

  return (
    <>
      <div>Example React useState: {number}</div>
      <div>Example React useContext: {exampleValue}</div>

      <Swiper
        modules={[Navigation, Pagination, Scrollbar, A11y]}
        spaceBetween={50}
        slidesPerView={3}
        navigation
        pagination={{ clickable: true }}
        scrollbar={{ draggable: true }}
        onSwiper={(swiper) => console.log(swiper)}
        onSlideChange={() => console.log("slide change")}
      >
        <SwiperSlide className="slide">Slide 1</SwiperSlide>
        <SwiperSlide className="slide">Slide 2</SwiperSlide>
        <SwiperSlide className="slide">Slide 3</SwiperSlide>
        <SwiperSlide className="slide">Slide 4</SwiperSlide>
        <SwiperSlide className="slide">Slide 5</SwiperSlide>
        <SwiperSlide className="slide">Slide 6</SwiperSlide>
        <SwiperSlide className="slide">Slide 7</SwiperSlide>
      </Swiper>
    </>
  );
};

export default ExampleComponent;
```

**Comment by gustavokei** [comment]
Sobre os outros pontos:

- Não precisa importar o `vtex.order-manager/OrderForm` no checkout
- Sobre instalação podemos entrar em contato caso ainda precise de auxílio, meu email está no meu perfil. Fora isso acabei de rever o fluxo de instalação e deixei anotado [aqui algumas observações](https://github.com/gustavokei/vtex-react-checkout/pull/2#issuecomment-1496096052)

**Comment by williamcms** [comment]
Muito obrigado pelas informações, vou analisar tudo certinho e se necessário, mando um email.
