### ISSUE TITLE
The react component doesn't appear in the checkout

### ISSUE THREAD

**Issue by dosegoe** [gustavokei/vtex-react-checkout#3]
Hi, this iniciative it's very innovative and looks useful, I really want to apply this on my store.

I tried both, the readme and this https://github.com/gustavokei/vtex-react-checkout/pull/2#issuecomment-1496096052, way of installing this app, but nothing happens.

As a resume...

- The readme way of installing it: in my vtex app I create a workspace, use "`vtex init`" in the terminal, install "checkout-ui-setting", this creates a folder with the "checkout-ui-custom" folder in it, there is where i clone this repository, in this repositorys folder I run `yarn`, `yarn dev`, and finally run `vtex link`. But nothing happens u.u
- The update way of installing it (https://github.com/gustavokei/vtex-react-checkout/pull/2#issuecomment-1496096052): inside the store's app folder i create a "checkout-ui-custom" folder with the checkout6-custom.css and checkout6-custom.js files; inside of this folder i clone this repository. In "vtex-react-checkout" I run `yarn,` `yarn dev` and finally `vtex link`, but again nothing happens.

¿What am I doing wrong? ¿Is there some previous configuration I'm missing?

Thank you, and congratulation for this iniciative.

**Comment by gustavokei** [comment]
Hi! Thank you for your feedback!

Please, try following these steps:
- Run `vtex init`

- Select `checkout-ui-settings`
![Screenshot 2023-05-22 at 10 27 43](https://github.com/gustavokei/vtex-react-checkout/assets/20908077/c6ac71a5-17f0-4ef2-8f97-5d657a52be1e)

- You should get the following folder structure:
![Screenshot 2023-05-22 at 10 29 00](https://github.com/gustavokei/vtex-react-checkout/assets/20908077/d146c316-f6ac-4c4d-8816-377f2249e5d3)

- Make sure you have the `checkout-ui-custom` builder in your `manifest.json` file
![Screenshot 2023-05-22 at 10 29 48](https://github.com/gustavokei/vtex-react-checkout/assets/20908077/3c909836-3f3d-4aa9-8a0b-64850d37fe93)

- Delete all files inside the `checkout-ui-custom` folder and clone or download this repository into it. Your files should be like this:
![Screenshot 2023-05-22 at 10 32 08](https://github.com/gustavokei/vtex-react-checkout/assets/20908077/831ef0fa-4745-4c52-bf73-844340e23156)

- Now, open a terminal in `checkout-ui-settings/checkout-ui-custom` path and run `yarn`, then `yarn dev`. This should start the webpack watcher:
![Screenshot 2023-05-22 at 10 35 06](https://github.com/gustavokei/vtex-react-checkout/assets/20908077/74e64602-35e7-4f14-8b32-914096c8e1a0)

- Make sure `checkout6-custom.js` and `checkout6-custom.css` were generated:
![Screenshot 2023-05-22 at 10 38 34](https://github.com/gustavokei/vtex-react-checkout/assets/20908077/f36a151b-4461-4671-9dd3-20238e567de3)

- Finally, run `vtex link` in your workspace and you should see a slider somewhere in `https://yourworkspace--youraccount.myvtex.com/checkout#/cart`
![app image](https://i.imgur.com/UDLqxW1.gif)

**Comment by dosegoe** [comment]
Now it works, thank you very much.

Some things that will make it clear is that `yarn` and `yarn dev` must be run in the folder where this repository files are. 

Thank you again!
