### ISSUE TITLE
Adding vtex.order-manager

### ISSUE THREAD

**Issue by Marcos-Iorio** [gustavokei/vtex-react-checkout#4]
Hi, i have a question on how to add vtex.order-manager to the checkout, because i add it to the manifest.json and package.json but when i try to import it on a React file typescript throws me an error on building that the module doesn't exists.

How can i fix this?

**Comment by gustavokei** [comment]
Hello! You might want to consider opening an issue on their respective repositories: https://github.com/vtex-apps/order-manager and https://github.com/vtex-apps/checkout-ui-settings. This project primarily serves as a plugin for checkout-ui-settings.

I'm going to close this issue for now as it appears to be unrelated to this repository. However, please don't hesitate to reopen it if you believe it's necessary. We're here to assist, and your input is always appreciated.
